create table orders
(
    id         integer generated by default as identity
        primary key,
    count      integer not null,
    date_time  timestamp,
    number     varchar(255),
    price      real    not null,
    status     integer,
    person_id  integer not null
        constraint fk1b0m4muwx1t377w9if3w6wwqn
            references person,
    product_id integer not null
        constraint fk787ibr3guwp6xobrpbofnv7le
            references product
);

alter table orders
    owner to postgres;

INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (1, 1, '2022-11-30 21:36:20.488758', 'cd308520-a30a-403f-903f-b099e3586118', 3, 5, 2, 3);
INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (2, 1, '2022-11-30 21:47:23.065119', '75d1f166-2c84-4540-b484-7dbc5e337548', 3, 5, 2, 3);
INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (3, 1, '2022-12-01 21:34:41.689564', '07830076-2656-494a-bdd3-3d4989956a2d', 2191, 5, 2, 3);
INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (4, 1, '2022-12-01 21:35:09.154849', 'a47e7321-7153-484f-87a9-3c1c93179a9c', 3690, 5, 2, 4);
INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (5, 1, '2022-12-01 21:35:37.664923', 'd566175c-fb08-4c98-9962-9c32286effc0', 3690, 5, 2, 4);
INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (6, 1, '2022-12-01 22:11:17.095059', 'f38efd85-9b17-4e42-b524-e2f34eac485c', 2191, 5, 2, 3);
INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (7, 1, '2022-12-01 22:11:17.125040', 'f38efd85-9b17-4e42-b524-e2f34eac485c', 3690, 5, 2, 4);
INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (8, 1, '2022-12-01 22:11:17.130037', 'f38efd85-9b17-4e42-b524-e2f34eac485c', 2191, 5, 2, 3);
INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (9, 1, '2022-12-01 22:11:17.135034', 'f38efd85-9b17-4e42-b524-e2f34eac485c', 2191, 5, 2, 3);
INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (10, 1, '2022-12-01 22:11:17.140030', 'f38efd85-9b17-4e42-b524-e2f34eac485c', 2191, 5, 2, 3);
INSERT INTO public.orders (id, count, date_time, number, price, status, person_id, product_id) VALUES (11, 1, '2022-12-01 22:11:17.147024', 'f38efd85-9b17-4e42-b524-e2f34eac485c', 2191, 5, 2, 3);
