create table image
(
    id         integer generated by default as identity
        primary key,
    file_name  varchar(255),
    product_id integer not null
        constraint fkgpextbyee3uk9u6o2381m7ft1
            references product
);

alter table image
    owner to postgres;

INSERT INTO public.image (id, file_name, product_id) VALUES (1, 'f7160834-6a4b-4e53-b6c7-917b0ab5d1bf.001.png', 3);
INSERT INTO public.image (id, file_name, product_id) VALUES (2, 'b023b1cd-8ebf-4ae3-a9ef-0a080ce8a97f.002.png', 3);
INSERT INTO public.image (id, file_name, product_id) VALUES (3, '2f6b4efa-70ce-4287-9cc3-6a10ebc64513.003.png', 3);
INSERT INTO public.image (id, file_name, product_id) VALUES (4, 'a4a4d7a1-db83-42e8-a66c-884ec7051bba.004.png', 3);
INSERT INTO public.image (id, file_name, product_id) VALUES (5, '4231e3e7-3c32-412a-a0e3-ecfce704e986.005.png', 3);
INSERT INTO public.image (id, file_name, product_id) VALUES (6, '971a66d5-7f1d-420a-94ee-9a13e68b0fe0.005.png', 4);
INSERT INTO public.image (id, file_name, product_id) VALUES (7, '7ab3f0ee-701c-4fd5-b7ac-5ce25d68711a.001.png', 4);
INSERT INTO public.image (id, file_name, product_id) VALUES (8, '47ad1c0e-b90a-48dd-9789-c19b4888dde4.003.png', 4);
INSERT INTO public.image (id, file_name, product_id) VALUES (9, '01ac8486-576d-4cde-b2ff-ae1afa1e3585.003.png', 4);
INSERT INTO public.image (id, file_name, product_id) VALUES (10, '3ba815cf-ab30-41ab-bfa3-81df5c7f0992.004.png', 4);
