create table person
(
    id       integer generated by default as identity
        primary key,
    login    varchar(100),
    password varchar(255),
    role     varchar(255)
);

alter table person
    owner to postgres;

INSERT INTO public.person (id, login, password, role) VALUES (1, 'admin', '$2a$10$jIsp2y0DzVDVDzTtztp2n.ItFDX4Z8tBEYoBR2UahisF3nbntUgnq', 'ROLE_ADMIN');
INSERT INTO public.person (id, login, password, role) VALUES (2, 'user_test', '$2a$10$ldrzAazlUwwsDNzUEF2TcuoObCK7oypSFc0KId.tMN23fnkbJB6TS', 'ROLE_USER');
