create table product_cart
(
    id         integer generated by default as identity
        primary key,
    person_id  integer
        constraint fksgnkc1ko2i1o9yr2p63ysq3rn
            references person,
    product_id integer
        constraint fkhpnrxdy3jhujameyod08ilvvw
            references product
);

alter table product_cart
    owner to postgres;

INSERT INTO public.product_cart (id, person_id, product_id) VALUES (16, 2, 3);
INSERT INTO public.product_cart (id, person_id, product_id) VALUES (17, 2, 3);
